version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=kazeem
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=video-manager
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://kazeem:secret@postgres:5432/video-manager?sslmode=disable
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://kazeem:secret@postgres:5432/video-manager?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
