// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Annotation struct {
	ID        uuid.UUID    `json:"id"`
	VideoID   uuid.UUID    `json:"video_id"`
	UserID    uuid.UUID    `json:"user_id"`
	Type      string       `json:"type"`
	Note      string       `json:"note"`
	Title     string       `json:"title"`
	Label     string       `json:"label"`
	Pause     bool         `json:"pause"`
	StartTime string       `json:"start_time"`
	EndTime   string       `json:"end_time"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Metadata struct {
	ID           uuid.UUID      `json:"id"`
	VideoID      uuid.UUID      `json:"video_id"`
	Width        int32          `json:"width"`
	Height       int32          `json:"height"`
	FileType     string         `json:"file_type"`
	FileSize     sql.NullString `json:"file_size"`
	LastModify   time.Time      `json:"last_modify"`
	AccessedDate time.Time      `json:"accessed_date"`
	Resolutions  int32          `json:"resolutions"`
	Keywords     string         `json:"keywords"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	UserName          string    `json:"user_name"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Video struct {
	ID        uuid.UUID `json:"id"`
	Url       string    `json:"url"`
	UserID    uuid.UUID `json:"user_id"`
	Duration  string    `json:"duration"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
