// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error)
	CreateMetadata(ctx context.Context, arg CreateMetadataParams) (Metadata, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteAnnotation(ctx context.Context, arg DeleteAnnotationParams) error
	DeleteMetadata(ctx context.Context, videoID uuid.UUID) error
	DeleteVideo(ctx context.Context, arg DeleteVideoParams) error
	GetAVideoAndMetadata(ctx context.Context, arg GetAVideoAndMetadataParams) (GetAVideoAndMetadataRow, error)
	GetAnnotation(ctx context.Context, arg GetAnnotationParams) (Annotation, error)
	GetMetadata(ctx context.Context, videoID uuid.UUID) (Metadata, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, userName string) (User, error)
	GetVideo(ctx context.Context, arg GetVideoParams) (Video, error)
	ListAnnotations(ctx context.Context, arg ListAnnotationsParams) ([]Annotation, error)
	ListVideos(ctx context.Context, arg ListVideosParams) ([]ListVideosRow, error)
	UpdateAnnotation(ctx context.Context, arg UpdateAnnotationParams) (Annotation, error)
	UpdateMetadata(ctx context.Context, arg UpdateMetadataParams) (Metadata, error)
	UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
